### PR TITLE
Add quotes to build messages

### PR DESCRIPTION
**Pull request by hardyoyo**
The following changes were required in order to build maven-notifier with Java 8, and to utilize the resulting Jar file Maven extension on Linux. The notify-send command really needs the message body to be quoted, or it is misinterpreted by the shell. This code compiles and has been tested in my own working environment.

### CODE REVIEW

**Comment by jcgay** [comment]
Thx I'll give it a try this week!

**Comment by jcgay** [comment]
Sorry for the late reply...

I've just give it a try and I'm kind of lost with your problem because I can't reproduce it. I'm gonna comment on #20.

Your change introduces single quotes around the notification message but what I get is effectively single quotes printed in the notification (they are not understood by the shell as delimiters). Do I missed something ?

**Comment by hardyoyo** [comment]
Interesting. What shell are you using?

**Comment by jcgay** [comment]
```
$> echo $SHELL
/bin/bash

$> /bin/bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

But I'm not sure this is relevant, a `Process` run by the JVM is not executed in the context of a shell ?
I've added additional logs in the latest SNAPSHOT in #20, could you give it a try ?

Thx

**Comment by jcgay** [comment]
Feel free to re-open if it's still actual.

**Pull request closed without merging**
